### ISSUE TITLE
snail popup window get maximum when i run `snails`.

### ISSUE THREAD

**Issue by zw963** [manateelazycat/snails#72]
When i run `snails` from helm, i get stucked on following window.

![image](https://user-images.githubusercontent.com/549126/132463898-791c9aef-1ad2-4da5-b436-4a2b289a2a42.png)

I even can't exit this buffer successful, i get minibuffer message like this:

![image](https://user-images.githubusercontent.com/549126/132464635-9a8c406f-973f-43bb-a30b-45d2e3b853de.png)

I can confirm this issue cause by my own config like this:

https://github.com/zw963/.emacs.d/blob/master/base_init.el#L259

this config is used for always maximum current frame if open a file use emacsclient, 
But, anyway, i consider this config should not change snails behavior, thanks.

-----------

Another issue is, after i comment my maximum frame code,  pop window works as expected. but get following error.

Symbol’s function definition is void: string-replace

and still can not exist emacs when i `C-x C-c` with same error message:

Attempt to delete a surrogate minibuffer frame

**Comment by manateelazycat** [comment]
I have fixed string-replace problem, it include in emacs 28.1

Nothing i can do for your frame maximium config, I suggest don't do that.

**Comment by zw963** [comment]
> Nothing i can do for your frame maximium config, I suggest don't do that.

Okay, i can try skip maximum in my config, though i still think there is a way to not respect my own maximum frame config, as like helm/ivy. (they both not maximum)


And,  `Attempt to delete a surrogate minibuffer frame`, this issue still exist, and can be reproduce with minimum config, and following is debug messages.

```
Debugger entered--Lisp error: (error "Attempt to delete a surrogate minibuffer frame")
  #<subr delete-frame>(nil nil)
  funcall(#<subr delete-frame> nil nil)
  (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force))
  (closure (snails-mode-abbrev-table snails-mode-syntax-table t) (orig &optional frame force) "Makes snails-frame undeletable. unless argument fo..." (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force)))(#<subr delete-frame>)
  apply((closure (snails-mode-abbrev-table snails-mode-syntax-table t) (orig &optional frame force) "Makes snails-frame undeletable. unless argument fo..." (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force))) #<subr delete-frame> nil)
  delete-frame()
  server-save-buffers-kill-terminal(nil)
  #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>)(nil)
  funcall(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
  (let ((auto-compile-mark-failed-modified nil)) (funcall fn arg))
  save-buffers-kill-terminal@auto-compile(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
  apply(save-buffers-kill-terminal@auto-compile #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)
```

BTW, this issue only happen on emacs daemon mode, following is reproduce

1.  add to path, require snails
2.  start emacs with `emacs --daemon`
3.  open a new frame use: `emacsclient -nc`
4. run snails, it works.
5. when try to close this frame with `C-x C-c`, get above error.

**Comment by manateelazycat** [comment]
> > Nothing i can do for your frame maximium config, I suggest don't do that.
> 
> Okay, i can try skip maximum in my config, though i still think there is a way to not respect my own maximum frame config, as like helm/ivy. (they both not maximum)
> 
> And, `Attempt to delete a surrogate minibuffer frame`, this issue still exist, and can be reproduce with minimum config, and following is debug messages.
> 
> ```
> Debugger entered--Lisp error: (error "Attempt to delete a surrogate minibuffer frame")
>   #<subr delete-frame>(nil nil)
>   funcall(#<subr delete-frame> nil nil)
>   (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force))
>   (closure (snails-mode-abbrev-table snails-mode-syntax-table t) (orig &optional frame force) "Makes snails-frame undeletable. unless argument fo..." (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force)))(#<subr delete-frame>)
>   apply((closure (snails-mode-abbrev-table snails-mode-syntax-table t) (orig &optional frame force) "Makes snails-frame undeletable. unless argument fo..." (if (or (and snails-frame (equal snails-frame frame) (null force)) (and (null frame) (snails-frame-is-active-p) (null force))) nil (funcall orig frame force))) #<subr delete-frame> nil)
>   delete-frame()
>   server-save-buffers-kill-terminal(nil)
>   #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>)(nil)
>   funcall(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
>   (let ((auto-compile-mark-failed-modified nil)) (funcall fn arg))
>   save-buffers-kill-terminal@auto-compile(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
>   apply(save-buffers-kill-terminal@auto-compile #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x1fcb2cae5913>) nil)
>   save-buffers-kill-terminal(nil)
>   funcall-interactively(save-buffers-kill-terminal nil)
>   call-interactively(save-buffers-kill-terminal nil nil)
>   command-execute(save-buffers-kill-terminal)
> ```
> 
> BTW, this issue only happen on emacs daemon mode, following is reproduce
> 
> 1. add to path, require snails
> 2. start emacs with `emacs --daemon`
> 3. open a new frame use: `emacsclient -nc`
> 4. run snails, it works.
> 5. when try to close this frame with `C-x C-c`, get above error.

you need   (setq snails-show-with-frame nil)
